-- ============================================================
-- PRECY+ — Migration 016: Hardening de Segurança Multi-Tenant
-- ============================================================
-- SUBSTITUÍDA por 016_security_hardening_v2.sql.
--
-- Esta versão tentava criar a função helper em `auth.user_company_id()`,
-- mas o schema `auth` é restrito em projetos Supabase gerenciados —
-- `CREATE FUNCTION` nele falha com "permission denied for schema auth"
-- quando aplicado via API/ferramentas de migration (só funciona rodando
-- manualmente como owner do banco no SQL Editor). A v2 refaz tudo isso em
-- `public.get_user_company_id()`, sem essa restrição, e já cobre 100% do
-- que este arquivo fazia (RLS, policies, tabelas, colunas e storage).
--
-- Mantido como no-op (em vez de removido) para preservar a numeração e o
-- histórico de migrations; não executa nada.
-- ============================================================
